// src/actions/image.js

module.exports.command = {
    name: 'img',
    aliases: ['resim', 'image', 'ciz', 'imagine'],
    description: 'action_image_desc',
    usage: '<prompt>'
};

module.exports.actionName = 'generate_image';

module.exports.execute = async function (sock, msg, params, app) {
    const { t } = app.utils;

    // get prompt
    let prompt = typeof params === 'string' ? params.trim() : params.prompt; // ai or user

    // is prompt empty
    if (!prompt) {
        await sock.sendMessage(msg.key.remoteJid, { text: t('action_image_error_usage') }, { quoted: msg });
        return;
    }

    // drawing reaction
    await sock.sendMessage(msg.key.remoteJid, { react: { text: '🎨', key: msg.key } });

    try {
        const { buffer, provider, model } = await app.services.ai.media.generateImage(prompt);

        // send img
        await sock.sendMessage(msg.key.remoteJid, {
            image: buffer,
            caption: `🎨 *${prompt}*` // \n\n_Generated by: ${provider} (${model})_ // debug
        }, { quoted: msg });

    } catch (error) {
        let errText = t('action_gen-image_error_general');

        if (error.response?.status === 503) {
            errText += ` (${t('action_gen-image_error_busy')})`;
        }

        if(error.response?.status === 429){
            errText += ` (${t('action_gen-image_error_ratelimit')})`;
        }

        await sock.sendMessage(msg.key.remoteJid, { text: errText }, { quoted: msg });
    }
};